services:
  web:
    build:
      context: ./web
      dockerfile: docker/Dockerfile.prod
    container_name: web
    restart: always
    depends_on:
      - backend
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`it-heodesk.vienthongact.vn`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT_BE}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT_BE}:${PORT_BE}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma generate && node src/server.js"
    restart: always
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`it-heodesk.vienthongact.vn`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=${PORT_BE}"

  db:
    image: postgres:18
    container_name: database
    profiles:
      - local-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirect HTTP → HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=boint@vienthongact.vn"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      # IP Whitelist middleware (global)
      - "--entrypoints.websecure.ipwhitelist.sourcerange=10.0.0.0/8, 192.168.0.0/16"

      # Rate limiting (global)
      - "--entrypoints.websecure.ratelimit.average=100"
      - "--entrypoints.websecure.ratelimit.burst=50"

      # Security headers (global)
      - "--entrypoints.websecure.headers.customframeoptionsvalue=SAMEORIGIN"
      - "--entrypoints.websecure.headers.contenttypenosniff=true"
      - "--entrypoints.websecure.headers.browserxssfilter=true"
      - "--entrypoints.websecure.headers.forceststheader=true"
      - "--entrypoints.websecure.headers.stsseconds=31536000"
      - "--entrypoints.websecure.headers.stsincludesubdomains=true"
      - "--entrypoints.websecure.headers.stspreload=true"

      # Logging
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"

      # API Dashboard (optional - production need off)
      - "--api.dashboard=false"
      # - "--api.dashboard=true"  # only need debug
      # - "--api.insecure=true"   # only need debug

  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./letsencrypt:/letsencrypt
    - ./logs:/var/log/traefik # save logs
  networks:
    - app-net
volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
