/*
  Warnings:

  - You are about to drop the column `EMPLOYEE_ID` on the `POSITIONS` table. All the data in the column will be lost.

*/
-- DropForeignKey
ALTER TABLE "POSITIONS" DROP CONSTRAINT "POSITIONS_EMPLOYEE_ID_fkey";

-- AlterTable
ALTER TABLE "EMPLOYEES" ADD COLUMN     "POSITION_ID" INTEGER;

-- AlterTable
ALTER TABLE "POSITIONS" DROP COLUMN "EMPLOYEE_ID";

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_POSITION_ID_fkey" FOREIGN KEY ("POSITION_ID") REFERENCES "POSITIONS"("POSITION_ID") ON DELETE SET NULL ON UPDATE CASCADE;
