/*
  Warnings:

  - You are about to drop the `Customer` table. If the table is not empty, all the data it contains will be lost.

*/
-- CreateEnum
CREATE TYPE "ENUMSTATUS" AS ENUM ('ENABLE', 'DISABLED');

-- CreateEnum
CREATE TYPE "NETWORK_STATUS" AS ENUM ('AVAILABLE', 'ASSIGNED', 'ACTIVE', 'INACTIVE', 'DISABLED', 'CONFLICT');

-- DropTable
DROP TABLE "Customer";

-- CreateTable
CREATE TABLE "COMPANY" (
    "COMPANY_ID" SERIAL NOT NULL,
    "COMPANY_NAME" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "COMPANY_pkey" PRIMARY KEY ("COMPANY_ID")
);

-- CreateTable
CREATE TABLE "DIVISIONS" (
    "DIVISION_ID" SERIAL NOT NULL,
    "DIVISION_NAME" TEXT NOT NULL,
    "COMPANY_ID" INTEGER NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DIVISIONS_pkey" PRIMARY KEY ("DIVISION_ID")
);

-- CreateTable
CREATE TABLE "ORG_UNITS" (
    "ORG_UNIT_ID" SERIAL NOT NULL,
    "UNIT_NAME" TEXT NOT NULL,
    "UNIT_TYPE" TEXT,
    "DIVISION_ID" INTEGER,
    "PARENT_UNIT_ID" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ORG_UNITS_pkey" PRIMARY KEY ("ORG_UNIT_ID")
);

-- CreateTable
CREATE TABLE "BRANCHES" (
    "BRANCH_ID" SERIAL NOT NULL,
    "BRANCH_NAME" TEXT NOT NULL,
    "LOCATION" TEXT,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "ORG_UNIT_ID" INTEGER,

    CONSTRAINT "BRANCHES_pkey" PRIMARY KEY ("BRANCH_ID")
);

-- CreateTable
CREATE TABLE "POSITIONS" (
    "POSITION_ID" SERIAL NOT NULL,
    "POSITION_NAME" TEXT NOT NULL,
    "LEVEL" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "NEW_COLUMN" BIGINT,
    "EMPLOYEE_ID" INTEGER,

    CONSTRAINT "POSITIONS_pkey" PRIMARY KEY ("POSITION_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEES" (
    "EMPLOYEE_ID" SERIAL NOT NULL,
    "EMPLOYEE_CODE" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "PHONE" TEXT,
    "EMAIL" TEXT,
    "BIRTH_DATE" DATE NOT NULL,
    "UNIT_ID" INTEGER,
    "VT_CODE" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMPLOYEES_pkey" PRIMARY KEY ("EMPLOYEE_ID")
);

-- CreateTable
CREATE TABLE "ACCOUNTS" (
    "ACCOUNT_ID" SERIAL NOT NULL,
    "PASSWORD" TEXT,
    "EMPLOYEE_ID" INTEGER,
    "IS_LOGIN" BOOLEAN NOT NULL DEFAULT false,
    "LOGIN" INTEGER NOT NULL DEFAULT 0,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ACCOUNTS_pkey" PRIMARY KEY ("ACCOUNT_ID")
);

-- CreateTable
CREATE TABLE "ACCOUNT_ROLES" (
    "AR_ID" SERIAL NOT NULL,
    "ACCOUNT_ID" INTEGER,
    "ROLE_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ACCOUNT_ROLES_pkey" PRIMARY KEY ("AR_ID")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "ROLE_ID" SERIAL NOT NULL,
    "ROLE_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "CREATED_BY" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "UPDATED_BY" TIMESTAMP(3) NOT NULL,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ROLE_ID")
);

-- CreateTable
CREATE TABLE "PERMISSIONS" (
    "PER_ID" SERIAL NOT NULL,
    "PER_NAME" TEXT NOT NULL,
    "GRANTED_BY" TIMESTAMP(3) NOT NULL,
    "REVOKED_AT" TIMESTAMP(3),
    "NOTES" TEXT,
    "ROLE_ID" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PERMISSIONS_pkey" PRIMARY KEY ("PER_ID")
);

-- CreateTable
CREATE TABLE "VLANS" (
    "VLAN_ID" INTEGER NOT NULL DEFAULT 1,
    "VLAN_NAME" TEXT NOT NULL,
    "NETWORK" TEXT NOT NULL,
    "DEFAULT_GATEWAY" TEXT,
    "SUBNET_MASK" TEXT,
    "IP_RANGE" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VLANS_pkey" PRIMARY KEY ("VLAN_ID")
);

-- CreateTable
CREATE TABLE "IPS" (
    "IP_ID" SERIAL NOT NULL,
    "HOST" TEXT NOT NULL,
    "VLAN_ID" INTEGER NOT NULL,
    "DEVICE_TYPE" TEXT,
    "EMPLOYEE_ID" INTEGER,
    "STATUS" "NETWORK_STATUS" NOT NULL DEFAULT 'INACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "IPS_pkey" PRIMARY KEY ("IP_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEE_VT" (
    "ID" SERIAL NOT NULL,
    "VT_CODE" INTEGER NOT NULL,
    "VT_EMAIL" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATE_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_AT" TIMESTAMP(3) NOT NULL,
    "VT_ID" INTEGER,

    CONSTRAINT "EMPLOYEE_VT_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEE_VT_VT_CODE_key" ON "EMPLOYEE_VT"("VT_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEE_VT_VT_EMAIL_key" ON "EMPLOYEE_VT"("VT_EMAIL");

-- AddForeignKey
ALTER TABLE "DIVISIONS" ADD CONSTRAINT "DIVISIONS_COMPANY_ID_fkey" FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY"("COMPANY_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORG_UNITS" ADD CONSTRAINT "ORG_UNITS_DIVISION_ID_fkey" FOREIGN KEY ("DIVISION_ID") REFERENCES "DIVISIONS"("DIVISION_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BRANCHES" ADD CONSTRAINT "BRANCHES_ORG_UNIT_ID_fkey" FOREIGN KEY ("ORG_UNIT_ID") REFERENCES "ORG_UNITS"("ORG_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POSITIONS" ADD CONSTRAINT "POSITIONS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_UNIT_ID_fkey" FOREIGN KEY ("UNIT_ID") REFERENCES "ORG_UNITS"("ORG_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNT_ROLES" ADD CONSTRAINT "ACCOUNT_ROLES_ACCOUNT_ID_fkey" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ACCOUNT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNT_ROLES" ADD CONSTRAINT "ACCOUNT_ROLES_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "PERMISSIONS_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IPS" ADD CONSTRAINT "IPS_VLAN_ID_fkey" FOREIGN KEY ("VLAN_ID") REFERENCES "VLANS"("VLAN_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IPS" ADD CONSTRAINT "IPS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE_VT" ADD CONSTRAINT "EMPLOYEE_VT_VT_ID_fkey" FOREIGN KEY ("VT_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
