-- CreateEnum
CREATE TYPE "ENUMSTATUS" AS ENUM ('ENABLE', 'DISABLED');

-- CreateEnum
CREATE TYPE "NETWORK_STATUS" AS ENUM ('AVAILABLE', 'ASSIGNED', 'ACTIVE', 'INACTIVE', 'DISABLED', 'CONFLICT');

-- CreateTable
CREATE TABLE "COMPANY" (
    "COMPANY_ID" SERIAL NOT NULL,
    "COMPANY_CODE" TEXT NOT NULL,
    "COMPANY_NAME" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "COMPANY_pkey" PRIMARY KEY ("COMPANY_ID")
);

-- CreateTable
CREATE TABLE "DIVISIONS" (
    "DIVISION_ID" SERIAL NOT NULL,
    "DIVISION_CODE" TEXT NOT NULL,
    "DIVISION_NAME" TEXT NOT NULL,
    "COMPANY_ID" INTEGER NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DIVISIONS_pkey" PRIMARY KEY ("DIVISION_ID")
);

-- CreateTable
CREATE TABLE "ORG_UNITS" (
    "ORG_UNIT_ID" SERIAL NOT NULL,
    "UNIT_CODE" TEXT NOT NULL,
    "UNIT_NAME" TEXT NOT NULL,
    "UNIT_TYPE" TEXT,
    "DIVISION_ID" INTEGER,
    "PARENT_UNIT_ID" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ORG_UNITS_pkey" PRIMARY KEY ("ORG_UNIT_ID")
);

-- CreateTable
CREATE TABLE "BRANCHES" (
    "BRANCH_ID" SERIAL NOT NULL,
    "BRANCH_CODE" TEXT NOT NULL,
    "BRANCH_NAME" TEXT NOT NULL,
    "LOCATION" TEXT,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "ORG_UNIT_ID" INTEGER,

    CONSTRAINT "BRANCHES_pkey" PRIMARY KEY ("BRANCH_ID")
);

-- CreateTable
CREATE TABLE "POSITIONS" (
    "POSITION_ID" SERIAL NOT NULL,
    "POSITION_CODE" TEXT NOT NULL,
    "POSITION_NAME" TEXT NOT NULL,
    "LEVEL" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "POSITIONS_pkey" PRIMARY KEY ("POSITION_ID")
);

-- CreateTable
CREATE TABLE "EMPLOYEES" (
    "EMPLOYEE_ID" SERIAL NOT NULL,
    "POSITION_CODE" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "PHONE" TEXT,
    "EMAIL" TEXT,
    "BIRTH_DATE" DATE,
    "UNIT_ID" INTEGER,
    "VIETTEL_ID" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "POSITION_ID" INTEGER,

    CONSTRAINT "EMPLOYEES_pkey" PRIMARY KEY ("EMPLOYEE_ID")
);

-- CreateTable
CREATE TABLE "ACCOUNTS" (
    "ACCOUNT_ID" SERIAL NOT NULL,
    "ACCOUNT_CODE" TEXT NOT NULL,
    "PASSWORD" TEXT,
    "IS_LOGIN" BOOLEAN NOT NULL DEFAULT false,
    "LOGIN" INTEGER NOT NULL DEFAULT 0,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "EMPLOYEE_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ACCOUNTS_pkey" PRIMARY KEY ("ACCOUNT_ID")
);

-- CreateTable
CREATE TABLE "ACCOUNT_ROLES" (
    "AR_ID" SERIAL NOT NULL,
    "AR_CODE" TEXT NOT NULL,
    "ROLE_ID" INTEGER,
    "ACCOUNT_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ACCOUNT_ROLES_pkey" PRIMARY KEY ("AR_ID")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "ROLE_ID" SERIAL NOT NULL,
    "ROLE_CODE" INTEGER NOT NULL,
    "ROLE_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "CREATED_BY" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "UPDATED_BY" TIMESTAMP(3) NOT NULL,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ROLE_ID")
);

-- CreateTable
CREATE TABLE "PERMISSIONS" (
    "PER_ID" SERIAL NOT NULL,
    "PER_CODE" INTEGER NOT NULL,
    "PER_NAME" TEXT NOT NULL,
    "GRANTED_BY" TIMESTAMP(3) NOT NULL,
    "REVOKED_AT" TIMESTAMP(3),
    "NOTES" TEXT,
    "ROLE_ID" INTEGER,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PERMISSIONS_pkey" PRIMARY KEY ("PER_ID")
);

-- CreateTable
CREATE TABLE "VLANS" (
    "VLAN_ID" INTEGER NOT NULL DEFAULT 1,
    "VLAN_CODE" INTEGER NOT NULL,
    "VLAN_NAME" TEXT NOT NULL,
    "NETWORK" TEXT,
    "DEFAULT_GATEWAY" TEXT,
    "SUBNET_MASK" TEXT,
    "IP_RANGE" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VLANS_pkey" PRIMARY KEY ("VLAN_ID")
);

-- CreateTable
CREATE TABLE "IPS" (
    "IP_ID" SERIAL NOT NULL,
    "HOST" TEXT NOT NULL,
    "VLAN_ID" INTEGER NOT NULL,
    "DEVICE_TYPE" TEXT,
    "EMPLOYEE_ID" INTEGER,
    "STATUS" "NETWORK_STATUS" NOT NULL DEFAULT 'INACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "IPS_pkey" PRIMARY KEY ("IP_ID")
);

-- CreateTable
CREATE TABLE "VIETTEL_EMPLOYEES" (
    "VIETTEL_ID" SERIAL NOT NULL,
    "VIETTEL_CODE" TEXT NOT NULL,
    "VIETTEL_EMAIL" TEXT NOT NULL,
    "STATUS" "ENUMSTATUS" NOT NULL DEFAULT 'ENABLE',
    "CREATE_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_AT" TIMESTAMP(3) NOT NULL,
    "EMPLOYEE_ID" INTEGER,

    CONSTRAINT "VIETTEL_EMPLOYEES_pkey" PRIMARY KEY ("VIETTEL_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "COMPANY_COMPANY_CODE_key" ON "COMPANY"("COMPANY_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "DIVISIONS_DIVISION_CODE_key" ON "DIVISIONS"("DIVISION_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "ORG_UNITS_UNIT_CODE_key" ON "ORG_UNITS"("UNIT_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "BRANCHES_BRANCH_CODE_key" ON "BRANCHES"("BRANCH_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "POSITIONS_POSITION_CODE_key" ON "POSITIONS"("POSITION_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEES_POSITION_CODE_key" ON "EMPLOYEES"("POSITION_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "ACCOUNTS_ACCOUNT_CODE_key" ON "ACCOUNTS"("ACCOUNT_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "ACCOUNT_ROLES_AR_CODE_key" ON "ACCOUNT_ROLES"("AR_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_ROLE_CODE_key" ON "ROLES"("ROLE_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "PERMISSIONS_PER_CODE_key" ON "PERMISSIONS"("PER_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "VLANS_VLAN_CODE_key" ON "VLANS"("VLAN_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "VIETTEL_EMPLOYEES_VIETTEL_CODE_key" ON "VIETTEL_EMPLOYEES"("VIETTEL_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "VIETTEL_EMPLOYEES_VIETTEL_EMAIL_key" ON "VIETTEL_EMPLOYEES"("VIETTEL_EMAIL");

-- AddForeignKey
ALTER TABLE "DIVISIONS" ADD CONSTRAINT "DIVISIONS_COMPANY_ID_fkey" FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANY"("COMPANY_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORG_UNITS" ADD CONSTRAINT "ORG_UNITS_DIVISION_ID_fkey" FOREIGN KEY ("DIVISION_ID") REFERENCES "DIVISIONS"("DIVISION_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BRANCHES" ADD CONSTRAINT "BRANCHES_ORG_UNIT_ID_fkey" FOREIGN KEY ("ORG_UNIT_ID") REFERENCES "ORG_UNITS"("ORG_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_UNIT_ID_fkey" FOREIGN KEY ("UNIT_ID") REFERENCES "ORG_UNITS"("ORG_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_POSITION_ID_fkey" FOREIGN KEY ("POSITION_ID") REFERENCES "POSITIONS"("POSITION_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNT_ROLES" ADD CONSTRAINT "ACCOUNT_ROLES_ACCOUNT_ID_fkey" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS"("ACCOUNT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACCOUNT_ROLES" ADD CONSTRAINT "ACCOUNT_ROLES_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PERMISSIONS" ADD CONSTRAINT "PERMISSIONS_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IPS" ADD CONSTRAINT "IPS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "IPS" ADD CONSTRAINT "IPS_VLAN_ID_fkey" FOREIGN KEY ("VLAN_ID") REFERENCES "VLANS"("VLAN_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VIETTEL_EMPLOYEES" ADD CONSTRAINT "VIETTEL_EMPLOYEES_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
