FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install --omit=dev

RUN npx prisma generate

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "npx prisma migrate deploy && node src/server.js"]
