-- CreateIndex
CREATE INDEX "ORG_UNITS_DIVISION_ID_idx" ON "ORG_UNITS"("DIVISION_ID");

-- CreateIndex
CREATE INDEX "ORG_UNITS_PARENT_UNIT_ID_idx" ON "ORG_UNITS"("PARENT_UNIT_ID");

-- AddForeignKey
ALTER TABLE "ORG_UNITS" ADD CONSTRAINT "ORG_UNITS_PARENT_UNIT_ID_fkey" FOREIGN KEY ("PARENT_UNIT_ID") REFERENCES "ORG_UNITS"("ORG_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
