name: Github CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if .env file is committed
        run: |
          if [ -f .env ] || [ -f web/.env ]; then
            echo "ERROR: .env file should not be committed to the repository!"
            exit 1
          fi

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install backend dependencies
        run: yarn install

      - name: Run Backend Lint (yarn lint)
        run: yarn lint